sudo: true
language: cpp

matrix:
  include:
  
  # Ubuntu, g++-7
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - ubuntu-sdk-team
        - sourceline: 'ppa:mhier/libboost-latest'
        packages:        
        - boost1.67
        - qtbase5-dev
        - g++-7
        - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-g++-7"
    - Deploy ="true"
    
  # OSX, clang
  - os: osx
    osx_image: xcode10
    compiler: clang
    addons:
     homebrew:
      packages:
       - boost
       - qt5
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
    - LABEL="osx-clang"
    - Deploy ="true"
    
  before_install:
    - eval $MATRIX_EVAL
    - if [ $TRAVIS_OS_NAME = osx ]; then brew cask uninstall --force oclint || true ; fi
    - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc@7 ; fi
           
script:
- eval $MATRIX_EVAL
- git clone https://github.com/livenet123/Newton.git cryptonote
- mkdir build && cd build
- export CMAKE_PREFIX_PATH=/usr/local/opt/qt5/
- cmake -DCMAKE_BUILD_TYPE=Release .. && make

before_deploy:
- mkdir NewtonWallet-${TRAVIS_TAG}
- mv NewtonWallet NewtonWallet-${TRAVIS_TAG}/
- tar -cvfz NewtonWallet-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz NewtonWallet-${TRAVIS_TAG}/
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure:
  file:
    - NewtonWallet-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz
  skip_cleanup: true
  on:
    repo: livenet123/NewtonWallet
    tags: true
    condition: "$DEPLOY = true"
