sudo: true
language: cpp
compiler: gcc
env:
- CXXFLAGS="-std=gnu++11"
matrix:
  include:
  
  # Ubuntu, g++-4.9
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:        
        - libboost1.55-all-dev
        - g++-4.9
        - gcc-4.9
    env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9
    - LABEL="linux-g++-4.9"
    - STRIP="strip"
    
  # OSX, g++-4.9
  - os: osx
    osx_image: xcode10
    compiler: gcc
    addons:
     homebrew:
      packages:
       - boost
       - qt5
    update: true
    env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9
    - LABEL="osx-g++-4.9"
    - STRIP="strip"  
    
  # OSX, clang
  - os: osx
    osx_image: xcode10
    compiler: clang
    addons:
     homebrew:
      packages:
       - boost
       - qt5
    update: true
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
    - LABEL="osx-clang"
    - STRIP="strip"
    
  before_install:
    - eval $MATRIX_EVAL
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install qtbase5-dev
    - sudo apt-get install qt5-default qttools5-dev-tools
    - if [ $TRAVIS_OS_NAME = osx ];  then
      echo "Adding brewed Qt5 to path";
      export PATH=/usr/local/opt/qt5/bin:$PATH;
      qmake -v;
      fi
      
script:
- eval $MATRIX_EVAL
- git clone https://github.com/livenet123/Newton.git cryptonote
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Release -DQt5_DIR=$(brew --prefix qt)/lib/cmake/Qt5  .. && make

before_deploy:
- mkdir NewtonWallet-${TRAVIS_TAG}
- mv NewtonWallet NewtonWallet-${TRAVIS_TAG}/
- tar -cvfz NewtonWallet-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz NewtonWallet-${TRAVIS_TAG}/
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure:
  file:
    - NewtonWallet-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz
  skip_cleanup: true
  on:
    repo: livenet123/NewtonWallet
    tags: true
