sudo: true
language: cpp
compiler: gcc
env:
- CXXFLAGS="-std=gnu++11"
matrix:
  include:
  
  # Ubuntu, g++-4.9
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:        
        - libboost-all-dev
        - g++-4.9
        - gcc-4.9
    env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9
    - LABEL="linux-g++-4.9"
    - STRIP="strip"
    
  # OSX, g++-4.9
  - os: osx
    osx_image: xcode10
    compiler: gcc
    env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9
    - LABEL="osx-g++-4.9"
    - STRIP="strip"  
    
  # OSX, clang
  - os: osx
    osx_image: xcode10
    compiler: clang
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
    - LABEL="osx-clang"
    - STRIP="strip"
    
  before_install:
    - eval $MATRIX_EVAL

install:
# Need to uninstall oclint to get newer gcc installed https://github.com/travis-ci/travis-ci/issues/8826
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew cask uninstall --force oclint || true ; fi

- if [[ "$LABEL" == "osx" ]]; then brew install gcc@4.9 ; fi
- if [[ "$LABEL" == "osx" ]]; then brew install qt5 ; fi
- if [[ "$LABEL" == "osx" ]]; then brew link --force qt5 ; fi
- if [[ "$LABEL" == "osx" ]]; then sudo ln -s /usr/local/Cellar/qt/5.11.0/mkspecs /usr/local/mkspecs ; fi
- if [[ "$LABEL" == "osx" ]]; then sudo ln -s /usr/local/Cellar/qt/5.11.0/plugins /usr/local/plugins ; fi
- if [[ "$LABEL" == "linux" ]]; then sudo apt-get install qtbase5-dev
  -y  ; fi

script:
- eval $MATRIX_EVAL
- git clone https://github.com/livenet123/Newton.git cryptonote
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Release .. && make

before_deploy:
- mkdir NewtonWallet-${TRAVIS_TAG}
- mv NewtonWallet NewtonWallet-${TRAVIS_TAG}/
- tar -cvfz NewtonWallet-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz NewtonWallet-${TRAVIS_TAG}/
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure:
  file:
    - NewtonWallet-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz
  skip_cleanup: true
  on:
    repo: livenet123/NewtonWallet
    tags: true
